In [1]:

import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt


# Importing Library and Importing Library

In [2]:
data=pd.read_csv("Australia_weather1.csv")


# slicing data

In [3]:
x=data.iloc[:,[2,3,4,13,14,19,20,21]].values
y=data.iloc[:,-1].values

In [4]:
print(x)

[[19.6 31.4 0.6 ... 28.1 29.1 'No']
 [22.5 30.6 4.6 ... 28.2 29.2 'Yes']
 [19.7 30.5 0.0 ... 27.2 29.4 'No']
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [5]:
print(y)

['Yes' 'No' 'No' ... nan nan nan]


In [6]:
y=y.reshape(-1,1) #2D list
print(y)

[['Yes']
 ['No']
 ['No']
 ...
 [nan]
 [nan]
 [nan]]


In [7]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)
print(x)
print(y)

[[19.6 31.4 0.6 ... 28.1 29.1 'No']
 [22.5 30.6 4.6 ... 28.2 29.2 'Yes']
 [19.7 30.5 0.0 ... 27.2 29.4 'No']
 ...
 [10.2 19.5 0.0 ... 15.0 20.0 'No']
 [10.2 19.5 0.0 ... 15.0 20.0 'No']
 [10.2 19.5 0.0 ... 15.0 20.0 'No']]
[['Yes']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [8]:
from sklearn.preprocessing import LabelEncoder
#lv1=LabelEncoder()
#x[:,0]=lv1.fit_transform(x[:,0])
#lv2=LabelEncoder()
#x[:,4]=lv2.fit_transform(x[:,4])
#lv3=LabelEncoder()
#x[:,6]=lv3.fit_transform(x[:,6])
#lv4=LabelEncoder()
#x[:,7]=lv4.fit_transform(x[:,7])
lv5=LabelEncoder()
x[:,-1]=lv5.fit_transform(x[:,-1])
lv6=LabelEncoder()
y=lv6.fit_transform(y)


c:\Users\Bigil\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
print(x)

[[19.6 31.4 0.6 ... 28.1 29.1 0]
 [22.5 30.6 4.6 ... 28.2 29.2 1]
 [19.7 30.5 0.0 ... 27.2 29.4 0]
 ...
 [10.2 19.5 0.0 ... 15.0 20.0 0]
 [10.2 19.5 0.0 ... 15.0 20.0 0]
 [10.2 19.5 0.0 ... 15.0 20.0 0]]


In [10]:
print(y)

[1 0 0 ... 0 0 0]


In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [12]:
print(x)

[[ 1.3171923   1.19528169 -0.14839977 ...  1.81654597  1.09766356
  -0.43654385]
 [ 1.82594993  1.07869335  0.49817794 ...  1.83331322  1.11314418
   2.29072064]
 [ 1.33473567  1.06411981 -0.24538643 ...  1.66564078  1.14410541
  -0.43654385]
 ...
 [-0.33188416 -0.5389699  -0.24538643 ... -0.37996299 -0.31107234
  -0.43654385]
 [-0.33188416 -0.5389699  -0.24538643 ... -0.37996299 -0.31107234
  -0.43654385]
 [-0.33188416 -0.5389699  -0.24538643 ... -0.37996299 -0.31107234
  -0.43654385]]


In [47]:
import pickle
pickle.dump(sc,open('scaling.pkl','wb'))

# spliting data into training and testing dataset

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [16]:
print(x_train)

[[ 1.35227904e+00  1.54504672e+00 -2.45386426e-01 ...  1.01171826e+00
   1.65496568e+00 -4.36543847e-01]
 [-3.31884158e-01 -5.38969899e-01 -2.45386426e-01 ... -3.79962991e-01
  -3.11072338e-01 -4.36543847e-01]
 [ 7.16132737e-02 -8.88734925e-01 -5.14131142e-02 ... -3.46428503e-01
  -1.08510305e+00  2.29072064e+00]
 ...
 [-2.10376418e+00  2.51183588e-04 -2.45386426e-01 ... -8.32678579e-01
   4.49817910e-02 -4.36543847e-01]
 [ 1.80840657e+00  1.95310591e+00 -2.45386426e-01 ...  1.81654597e+00
   2.02650042e+00 -4.36543847e-01]
 [-4.89774457e-01 -1.28222058e+00  7.56809017e-01 ... -9.33282043e-01
  -1.33279288e+00  2.29072064e+00]]


In [17]:
print(y_train)

[0 0 0 ... 0 0 1]


# training model

In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [44]:
x_train=sc.fit_transform(x_train)


In [43]:
x_test=sc.transform(x_test)
#y_test=sc.transform(y_test)

In [23]:
classifier.score(x_train,y_train)

0.9998282541075892

In [24]:
print(y_test)

[0 0 0 ... 0 0 0]


In [25]:
Y_test=y_test.reshape(-1,1)
print(Y_test)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [26]:
Y_pred=classifier.predict(x_test)
print(Y_pred)

[0 0 0 ... 0 1 0]


In [27]:
y_pred=lv6.inverse_transform(Y_pred)

In [28]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'Yes' 'No']


In [29]:
print(Y_test)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [30]:
Y_test=lv6.inverse_transform(Y_test)

c:\Users\Bigil\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [31]:
print(Y_test)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [32]:
Y_test=Y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)
print(Y_test)


[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [33]:
print(y_pred)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['Yes']
 ['No']]


In [34]:
df=np.concatenate((Y_test,y_pred),axis=1)
dataframe=pd.DataFrame(df,columns=['rain on tommorow(actual)','rain on tommorow(predicted)'])
print(dataframe)

      rain on tommorow(actual) rain on tommorow(predicted)
0                           No                          No
1                           No                          No
2                           No                          No
3                           No                          No
4                           No                          No
...                        ...                         ...
13096                       No                          No
13097                      Yes                          No
13098                       No                          No
13099                       No                         Yes
13100                       No                          No

[13101 rows x 2 columns]


In [35]:
dataframe.to_csv('prediction.csv')

# checking Accuracy range


In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8792458590947256

# pickling the model file for deployment

In [37]:
import pickle

In [41]:
pickle.dump(classifier,open('classifymodel.pkl','wb'))

In [42]:
pickled_model=pickle.load(open('classifymodel.pkl','rb'))

In [40]:
pickled_model.predict(x_test[0].reshape(1,-1))

array([0])